{{- if .Values.rbac.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "crate-operator.labels" . | nindent 4 }}
  name: {{ template "crate-operator.fullname" . }}
rules:
# Framework: posting the events about the handlers progress/errors
- apiGroups:
  - '*'
  resources:
  - '*'
  - '*/finalizers'
  - '*.*'
  - '*.*/finalizers'
  - persistentvolumes
  - persistentvolumes/*
  - persistentvolumes/finalizers
  - persistentvolumeclaims
  - persistentvolumeclaims/*
  - persistentvolumeclaims/finalizers
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "crate-operator.labels" . | nindent 4 }}
  name: {{ template "crate-operator.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "crate-operator.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "crate-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
